### ISSUE TITLE
What about licensing for this project? 

### ISSUE THREAD

**Issue by VladoCC** [ftomassetti/kllvm#3]

**Comment by ftomassetti** [comment]
Hi @VladoCC I would be happy to release it under the Apache License V2.0, if someone is providing a PR with the necessary changes (adding the License file and reference to it in the Readme)

**Comment by VladoCC** [comment]
Oh, that's not a problem
Will do that in a few hours

**Comment by VladoCC** [comment]
I'm planning to adopt this generator into Kotlin/Native project and create natively executable compiler with it, if you are curious
So, ability to change sources was a key for me :)

**Comment by VladoCC** [comment]
#4

**Comment by ftomassetti** [comment]
Thank you, this has been merged
